import type { Metadata } from "next";
import { Lexend } from "next/font/google";
import "./globals.css";
import Sidebar from "@/components/sidebar";

const lexend = Lexend({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={lexend.className}>
        <div className="flex">
          <aside className="w-1/4 h-screen flex items-center justify-centers">
            <Sidebar />
          </aside>
          {children}
        </div>
      </body>
    </html>
  );
}
